# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/hpoup/Desktop/space_invaders/space_invaders.cache/wt [current_project]
set_property parent.project_path C:/Users/hpoup/Desktop/space_invaders/space_invaders.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_cache_permissions disable [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/hpoup/Desktop/space_invaders/space_invaders.srcs/sources_1/new/charg_memoire.vhd
  C:/Users/hpoup/Desktop/space_invaders/space_invaders.srcs/sources_1/new/gest_command.vhd
  C:/Users/hpoup/Desktop/space_invaders/space_invaders.srcs/sources_1/new/vga_160_100.vhd
  C:/Users/hpoup/Desktop/space_invaders/space_invaders.srcs/sources_1/new/top_module.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/hpoup/Desktop/space_invaders/space_invaders.srcs/constrs_1/new/contrainte.xdc
set_property used_in_implementation false [get_files C:/Users/hpoup/Desktop/space_invaders/space_invaders.srcs/constrs_1/new/contrainte.xdc]


synth_design -top top_module -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top_module.dcp

catch { report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb }
